This is makeindex, version 2.17 [TeX Live 2025/dev] (kpathsea + Thai support).
Scanning style file ./rapport2.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file rapport2.acn....done (66 entries accepted, 0 rejected).
Sorting entries....done (471 comparisons).
Generating output file rapport2.acr....done (39 lines written, 0 warnings).
Output written in rapport2.acr.
Transcript written in rapport2.alg.
