This is makeindex, version 2.17 [TeX Live 2025/dev] (kpathsea + Thai support).
Scanning style file ./rapport7.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file rapport7.acn....done (57 entries accepted, 0 rejected).
Sorting entries....done (329 comparisons).
Generating output file rapport7.acr....done (65 lines written, 0 warnings).
Output written in rapport7.acr.
Transcript written in rapport7.alg.
