This is makeindex, version 2.17 [TeX Live 2025/dev] (kpathsea + Thai support).
Scanning style file ./rapport4.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file rapport4.acn....done (172 entries accepted, 0 rejected).
Sorting entries.....done (1523 comparisons).
Generating output file rapport4.acr....done (88 lines written, 0 warnings).
Output written in rapport4.acr.
Transcript written in rapport4.alg.
